'use strict';
const el = id => document.getElementById(id);
const esc = x => String(x).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number = (x,n=2) => x == null ? '—' : Number(x).toFixed(n);
let report = null, requestNumber = 0;
const labels = {original:'Original 65/35 model',fitted:'Early-season fitted blend',history:'History-average baseline',recent_three:'Last-three-game baseline',last_game:'Last-game baseline',always_montgomery:'Always start Montgomery',always_stevenson:'Always start Stevenson',hindsight_best:'Hindsight-best choice (not a forecast)'};
function table(headers,rows,caption='') { return `<div class="case-table-wrap"><table class="case-table">${caption?`<caption>${esc(caption)}</caption>`:''}<thead><tr>${headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`; }
function render(r) {
 const methods=r.later_evaluation.methods, pair=r.pair_case;
 const metricsRows=Object.keys(methods).map(k=>`<tr class="${k==='original'?'case-row-current':''}"><td>${esc(labels[k])}</td><td class="num">${number(r.training.methods[k].rmse)}</td><td class="num">${number(methods[k].rmse)}</td><td class="num">${number(methods[k].mae)}</td><td class="num">${methods[k].n}</td></tr>`);
 const weekly=pair.weeks.map(w=>{const [m,s]=w.players;return `<tr><td>Week ${w.week}<small>History through W${w.week-1}</small></td><td class="num">${number(m.original)}</td><td class="num">${number(s.original)}</td><td>${esc(w.decisions.original.name)}</td><td class="num">${number(m.actual,1)} / ${number(s.actual,1)}</td></tr>`;});
 const totalRows=Object.entries(pair.totals).map(([k,v])=>`<tr class="${k==='original'?'case-row-current':''}"><td>${esc(labels[k])}</td><td class="num">${number(v,1)}</td><td class="num">${k in pair.correct_weekly_choices?`${pair.correct_weekly_choices[k]} / ${pair.n}`:'Not a learned rule'}</td></tr>`);
 const inventory=[...r.roster.draft_roster,...r.roster.reported_additions];
 const people=inventory.map(p=>`<div class="case-person"><span class="case-pos">${esc(p.position)}</span><div><b>${esc(p.name)}</b><small>${esc(p.team_at_draft||p.team)} · ${p.statistical_data_bundled?'2025 data evaluated':'Inventory only — not evaluated'}${p.id==='stevenson'?' · Reported playoff addition':''}</small></div></div>`).join('');
 const sourceLinks=r.data.manifest.sources.map(s=>`<p class="case-source"><b>${esc(s.name)}</b> — <a href="${esc(s.fantasy_points_and_receptions)}" target="_blank" rel="noopener noreferrer">Published fantasy statistics</a> · <a href="${esc(s.week_mapping_and_box_score_reference)}" target="_blank" rel="noopener noreferrer">NFL week / box-score reference</a></p>`).join('');
 const rawRows=r.player_forecasts.filter(p=>p.week>=15).sort((a,b)=>a.week-b.week||a.name.localeCompare(b.name)).map(p=>`<tr><td>W${p.week}</td><td>${esc(p.name)}</td><td class="num">${number(p.history)}</td><td class="num">${number(p.recent_weighted)}</td><td class="num">${number(p.original)}</td><td class="num">${number(p.actual,1)}</td></tr>`);
 el('case-content').innerHTML=`
 <div class="case-note"><b>Scope: four running backs, not a replay of the entire championship.</b> Achane, Montgomery, Harvey and Stevenson supply the statistical test. The full drafted roster is inventoried below. Scoring, the W15–17 comparison window and Stevenson's availability date are scenario inputs — not verified league settings.</div>
 <div class="stats-grid case-stat-grid"><div class="stat"><div class="stat-label">SOURCE OBSERVATIONS</div><div class="stat-value">${r.data.records}<small>player-games</small></div><div class="stat-detail">4 running backs · 2025 regular season</div></div><div class="stat"><div class="stat-label">LATER-WEEK MODEL ERROR</div><div class="stat-value">${number(methods.original.rmse)}<small>RMSE</small></div><div class="stat-detail">${r.later_evaluation.n} observed cases · weeks 11–17</div></div><div class="stat"><div class="stat-label">EARLY-SEASON FIT</div><div class="stat-value">${number(r.fit.alpha,2)}<small>recency weight</small></div><div class="stat-detail">Fitted on ${r.fit.n} cases through week 10 only</div></div></div>
 <section class="case-section"><h2>01 / Projection model & calibration</h2><p>Original parameters are preserved. One alternative recency coefficient is fitted on early weeks, then frozen for later-week evaluation.</p><div class="case-grid"><div class="case-code">Original projection<br><b>0.65 × recent + 0.35 × history</b><p>Recent = last six observed games, newest weight 1, then 0.75, 0.75², and so on. History = average of all loaded games before the decision week. Missing appearances are not zero-filled.</p></div><div class="case-code">Fitted alternative<br><b>${number(r.fit.alpha,2)} × recent + ${number(1-r.fit.alpha,2)} × history</b><p>The coefficient minimizes early-season squared error and is restricted to 0–1. A zero result means this small training set does not support adding a positive recency weight. The fit selects the historical mean on this sample; the original model remains available for comparison.</p></div></div><p class="case-context">The season and roster were selected after the outcome was known. The time split prevents later-game outcomes from entering the fit; it does not make the study an untouched future test.</p></section>
 <section class="case-section"><h2>02 / Forecast benchmark</h2><p>Lower error is better. RMSE penalizes large misses more heavily; MAE is the average absolute miss. Both are displayed so one favorable metric cannot hide another.</p>${table(['Method','Training RMSE · W4–10','Later RMSE · W11–17','Later MAE','Later cases'],metricsRows)}<p class="case-context">Only the same observed, non-bye player-weeks with sufficient prior history are scored. Absences and eligibility exclusions remain visible in the exported report. These are conditional forecasting errors, not league wins.</p></section>
 <section class="case-section"><h2>03 / Stevenson or Montgomery?</h2><p>One interchangeable RB/FLEX slot, assuming both players are owned and available from week ${pair.assumed_acquisition_week}. Actual starts and transactions were not supplied. Projections use only completed earlier weeks.</p>${table(['Decision week','Montgomery forecast','Stevenson forecast','Original-model pick','Actual M / S'],weekly)}<div class="case-grid case-section"><div>${table(['Comparison','Realized points','Correct weekly choices'],totalRows,`Same ${pair.n} comparable week(s); all methods and fixed-player controls shown`)}</div><div class="case-note"><b>Interpretation</b><p>Choosing Stevenson over Montgomery in week 17 produces a favorable historical comparison. Missing him in earlier weeks is also part of the result. Always starting Stevenson is included as a control, even when it beats the model.</p><p>Neither comparison establishes that this software caused your championship or beat your actual lineup choices. WR/TE FLEX alternatives are outside this test.</p></div></div></section>
 <section class="case-section"><h2>04 / The complete personal roster</h2><p>17 drafted entries from your photo, plus the reported playoff addition. Only entries labeled “data evaluated” contribute to this statistical report.</p><div class="case-roster">${people}</div></section>
 <section class="case-section"><h2>05 / Inspect the evidence</h2><details><summary>Week 15–17 forecast components for the four-player subset</summary>${table(['Week','Player','History mean','Recent weighted','Original forecast','Actual'],rawRows)}</details><details><summary>Source provenance and scoring precision</summary>${sourceLinks}<p>${esc(r.data.manifest.precision_note)}</p><p>Stevenson scores include the two-point conversions in weeks 2 and 16. Historical publication vintages are not reconstructed.</p><p>Dataset SHA-256: <code>${esc(r.data.sha256)}</code></p></details><details><summary>Study boundaries and missing evidence</summary>${r.limits.map(t=>`<div class="case-limit">${esc(t)}</div>`).join('')}</details></section>`;
}
async function load(){const current=++requestNumber;el('case-content').setAttribute('aria-busy','true');el('case-error').hidden=true;el('export-case').disabled=true;try{const query=new URLSearchParams({scoring:el('case-scoring').value,acquired:el('case-acquired').value});const response=await fetch('/api/championship?'+query);const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to calculate the case.');if(current!==requestNumber)return;report=data;render(data);el('export-case').disabled=false;}catch(e){if(current===requestNumber){el('case-error').textContent=e.message;el('case-error').hidden=false;}}finally{if(current===requestNumber)el('case-content').setAttribute('aria-busy','false');}}
el('case-scoring').addEventListener('change',load);el('case-acquired').addEventListener('change',load);el('export-case').addEventListener('click',()=>{if(!report)return;const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`fourth-down-2025-${report.scoring}-from-week-${report.pair_case.assumed_acquisition_week}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});load();
