"""Generate the portable browser dataset from the tested Python implementation."""
import json
from pathlib import Path
from fourth_down.data import ROOT, Repository
from fourth_down.model import project, backtest

def build():
    repo = Repository()
    payload = {'meta': repo.metadata(), 'snapshots': {f'{w}-{s}': project(repo, 2024, w, s) for w in range(4, 17) for s in ('standard', 'half', 'ppr')}, 'audits': {s: backtest(repo, 2024, s) for s in ('standard', 'half', 'ppr')}, 'research': json.loads((ROOT / 'reports/research.json').read_text()), 'cloud': json.loads((ROOT / 'reports/cloud_setup_status.json').read_text())}
    (ROOT / 'site/data.js').write_text('/* Generated by python -m scripts.build_site; do not edit. */\nwindow.FOURTH_DOWN_DATA = ' + json.dumps(payload, separators=(',', ':'), allow_nan=False).replace('<', '\\u003c') + ';\n')
    print('Built portable dataset: real Python forecasts, three scoring formats, 13 decision weeks.')
if __name__ == '__main__':
    build()
